version: '3'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: emojition
      POSTGRES_USER: emojition
      POSTGRES_PASSWORD: emojition
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-tier
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: phamkhacquyen1996@gmail.com
      PGADMIN_DEFAULT_PASSWORD: phamkhacquyen1996
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-tier
volumes:
  db-data:
  pgadmin-data:
networks:
  app-tier:
    driver: bridge