db:
  host: localhost
  port: 5432
  user: emojition
  password: emojition
  database: emojition
  sslmode: disable
  timezone: Asia/SaiGon
auth:
  secret: EMOJITION_SECRET
server:
  host: localhost
  port: 8080